harvest_moon_haven/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('games/', views.games_list, name='index'),
    path('games/create', views.GameCreate.as_view(), name='game_create'),
    path('games/<int:pk>/update/', views.GameUpdate.as_view(), name='game_update'),
    path('games/<int:pk>/delete/', views.GameDelete.as_view(), name='game_delete'),
    path('games/<int:game_id>', views.game_detail, name='detail'),
    path('games/<int:game_id>/create_note', views.note_create, name='create_note'),
    path('notes/', views.my_notes, name='notes_index'),
    path('notes/<int:pk>/update/', views.NoteUpdate.as_view(), name='note_update'),
    path('notes/<int:pk>/delete/', views.NoteDelete.as_view(), name='delete_note'),
    path('games/<int:game_id>/all_bachelors', views.all_bachelors, name='bachelors'),
    path('bachelor/<int:pk>/', views.BachelorDetail.as_view(), name='bachelor_detail'),
    path('bachelor/<int:bachelor_id>/create_note', views.bachelor_createnote, name='bachelor_createnote'),
    path('bachelor/create', views.BachelorCreate.as_view(), name='bachelor_create'),
    path('bachelor/<int:pk>/update/', views.BachelorUpdate.as_view(), name='bachelor_update'),
    path('bachelor/<int:pk>/delete/', views.BachelorDelete.as_view(), name='bachelor_delete'),
    path('games/<int:game_id>/all_bachelorettes', views.all_bachelorettes, name='bachelorettes'),
    path('bachelorette/<int:pk>/', views.BacheloretteDetail.as_view(), name='bachelorette_detail'),
    path('bachelorette/<int:bachelorette_id>/create_note', views.bachelorette_createnote, name='bachelorette_createnote'),
    path('bachelorette/create_bachelorette', views.BacheloretteCreate.as_view(), name='bachelorette_create'),
    path('bachelorette/<int:pk>/update/', views.BacheloretteUpdate.as_view(), name='bachelorette_update'),
    path('bachelorette/<int:pk>/delete/', views.BacheloretteDelete.as_view(), name='bachelorette_delete'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date



# Create your models here.
class Game(models.Model):
    title = models.CharField(max_length=150)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.title}'
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'game_id': self.id})


class Bachelor(models.Model):
    loved = models.TextField(max_length=100)
    liked = models.TextField(max_length=100)
    neutral = models.TextField(max_length=100)
    disliked = models.TextField(max_length=100)
    hated = models.TextField(max_length=100)
    name = models.CharField(max_length=100)
    game = models.ForeignKey(Game, on_delete=models.CASCADE, blank=True, null=True, related_name='bachelors')

    def __str__(self):
        return f"{self.name}"
    
    def get_absolute_url(self):
        return reverse('bachelors', kwargs={'bachelors_id': self.id})

    
class Bachelorette(models.Model):
    loved = models.TextField(max_length=100)
    liked = models.TextField(max_length=100)
    neutral = models.TextField(max_length=100)
    disliked = models.TextField(max_length=100)
    hated = models.TextField(max_length=100)
    name = models.CharField(max_length=100)
    game = models.ForeignKey(Game, on_delete=models.CASCADE, blank=True, null=True, related_name='bachelorettes')
    
    def __str__(self):
        return f"{self.name}"
    
    def get_absolute_url(self):
        return reverse('bachelorettes', kwargs={'bachelorettes_id': self.id})


class Note(models.Model):
    title = models.CharField(max_length=100, default='null')
    content = models.TextField(max_length=3500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, related_name='notes', on_delete=models.CASCADE)
    bachelor = models.ForeignKey(Bachelor, on_delete=models.CASCADE, blank=True, null=True)
    bachelorette = models.ForeignKey(Bachelorette, on_delete=models.CASCADE, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.content}, {self.updated_at}' 
    
    class Meta:
        ordering = ['-updated_at']   
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'note_id': self.id})

main_app/forms.py
from django.forms import ModelForm
from .models import Note


class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'content']
        

main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from .models import Game, Note, Bachelor, Bachelorette
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from .forms import NoteForm

# Create your views here.
def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


def games_list(request):
    games = Game.objects.all()
    return render(request, 'games/index.html', {'games': games})


def game_detail(request, game_id):
    game = Game.objects.get(id=game_id)
    notes = Note.objects.filter(game=game_id)
    return render(request, 'games/detail.html', {'game': game, 'notes': notes})



class GameCreate(CreateView, LoginRequiredMixin):
    model = Game
    fields = ['title']
    
class GameUpdate(UpdateView, LoginRequiredMixin):
    model = Game
    fields = ['title']
    
class GameDelete(DeleteView, LoginRequiredMixin):
    model = Game
    success_url = '/games'



@login_required
def note_create(request, game_id):
    form = NoteForm(request.POST, use_required_attribute=False)
    if form.is_valid():
        new_note = form.save(commit=False)
        new_note.user = request.user
        new_note.game_id = game_id
        new_note.save()
        return redirect('detail', game_id)    
    return render(request,'main_app/note_form.html', {'form': form})
        
 

class NoteUpdate(UpdateView, LoginRequiredMixin):
    model = Note
    fields = ['title', 'content']
    template_name = 'main_app/note_update_form.html' 
    
    def get_success_url(self):
        return f"/games/{self.object.game.id}"   

class NoteDelete(DeleteView, LoginRequiredMixin):
    model = Note
    
    def get_success_url(self):
        return f"/games/{self.object.game.id}"



@login_required
def my_notes(request):
    notes = Note.objects.filter(user=request.user)
    games = Game.objects.all()
    bachelors = Bachelor.objects.all()
    bachelorettes = Bachelorette.objects.all()
    return render(request, 'notes/index.html', {'notes': notes, 'games': games, 'bachelors': bachelors, 'bachelorettes': bachelorettes})



def all_bachelors(request, game_id):
    game = Game.objects.get(id=game_id)
    return render(request, 'bachelor/index.html', {'game': game})

class BachelorCreate(CreateView, LoginRequiredMixin):
    model = Bachelor
    fields = ['name', 'loved', 'liked', 'neutral', 'disliked', 'hated', 'game']
    
    def get_success_url(self):
        return f'/games/{self.object.game.id}/all_bachelors'
    
class BachelorDetail(DetailView):
    model = Bachelor
    
class BachelorUpdate(UpdateView, LoginRequiredMixin):
    model = Bachelor
    fields = ['name', 'loved', 'liked', 'neutral', 'disliked', 'hated', 'game']
    template_name = 'main_app/bachelor_update_form.html'
    
    def get_success_url(self):
        return f"/games/{self.object.game.id}/all_bachelors"

class BachelorDelete(DeleteView, LoginRequiredMixin):
    model = Bachelor
    success_url = '/games/{game_id}/all_bachelors'
   
   
    
@login_required
def bachelor_createnote(request, bachelor_id):
    form = NoteForm(request.POST)
    bachelor = Bachelor.objects.get(id=bachelor_id)
    if form.is_valid():
        new_bachelor_note = form.save(commit=False)
        new_bachelor_note.user = request.user
        new_bachelor_note.bachelor_id = bachelor_id
        new_bachelor_note.game_id = bachelor.game_id
        new_bachelor_note.save()
        return redirect('bachelor_detail', bachelor_id)    
    return render(request,'main_app/note_form.html', {'form': form})



def all_bachelorettes(request, game_id):
    game = Game.objects.get(id=game_id)
    return render(request, 'bachelorette/index.html', {'game': game})
  
  
  
class BacheloretteCreate(CreateView, LoginRequiredMixin):
    model = Bachelorette
    fields = ['name', 'loved', 'liked', 'neutral', 'disliked', 'hated', 'game']
    
    def get_success_url(self):
        return f'/games/{self.object.game.id}/all_bachelorettes'
    
class BacheloretteDetail(DetailView):
    model = Bachelorette
    
class BacheloretteUpdate(UpdateView, LoginRequiredMixin):
        model = Bachelorette
        fields = ['name', 'loved', 'liked', 'neutral', 'disliked', 'hated', 'game']

        def get_success_url(self):
            return f'/games/{self.object.game.id}/all_bachelorettes'

class BacheloretteDelete(DeleteView, LoginRequiredMixin):
    model = Bachelorette
    success_url = '/games/{game_id}/all_bachelorettes'
  
  
  
@login_required
def bachelorette_createnote(request, bachelorette_id):
    form = NoteForm(request.POST)
    bachelorette = Bachelorette.objects.get(id=bachelorette_id)
    if form.is_valid():
        new_bachelorette_note = form.save(commit=False)
        new_bachelorette_note.user = request.user
        new_bachelorette_note.bachelorette_id = bachelorette_id
        new_bachelorette_note.game_id = bachelorette.game_id
        new_bachelorette_note.save()
        return redirect('bachelorette_detail', bachelorette_id)    
    return render(request,'main_app/note_form.html', {'form': form})



def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
        else:
            error_message = "Invalid signup - Please Try Again"
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

main_app/templates/main_app/bachelor_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="title-container">
  <h1>Delete Bachelor</h1>
</div>

  <h4>Are you sure you want to delete <span class="red-text">{{ bachelor.name }}</span>?</h4>

  <div class="form-container">
    <form action="" method="POST">
      {% csrf_token %}
      <input type="submit" value="Yes - Delete!" class="btn">
      <a href="{% url 'bachelors' object.game.id %}" class="cancel">Cancel</a>
    </form>
</div>

{% endblock %}

main_app/templates/main_app/bachelor_detail.html
{% extends 'base.html' %}

{% block content %}

<a href="javascript:history.back()" class="back">Back</a>
{% if object %}
<div class="title-container">
    <h1>{{ bachelor.name }}/{{ object.game.title }}</h1>
</div>
<div class="table-container">
    <table class="gifts">
        <thead>
            <tr>
                <th>Loved Gifts</th>
                <th>Liked Gifts</th>
                <th>Neutral Gifts</th>
                <th>Disliked Gifts</th>
                <th>Hated Gifts</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{bachelor.loved}}</td>&nbsp;
                <td>{{bachelor.liked}}</td>&nbsp;
                <td>{{bachelor.neutral}}</td>&nbsp;
                <td>{{bachelor.disliked}}</td>&nbsp;
                <td>{{bachelor.hated}}</td>&nbsp;
            </tr>
        </tbody>
    </table>
</div>

<a href="{% url 'bachelor_update' bachelor.id %}">Update Bachelor</a>&nbsp;


{% for note in bachelor.note_set.all %}
<div class="notes-content">
    <h2>{{ note.title }}</h2>
    <p>{{ note.updated_at }}</p>
    <p class="notecontent">{{ note.content }}</p>
</div>
{% endfor %}
<a href="{% url 'bachelor_createnote' bachelor.id %}">Create Note</a>
{% endif %}

{% endblock %}

main_app/templates/main_app/bachelor_form.html
{% extends 'base.html' %}

{% block content %}

<a href="javascript:history.back()" class="back">Back</a>

<div class="title-container">
    <h1>Add Bachelor</h1>
</div>



    <form action="" method="POST">
        {% csrf_token %}
        <table class="gifts">
            {{ form.as_table }}
        </table>
        <input type="submit" value="Add Bachelor" class="add-bachelorbtn">
    </form>

    
{% endblock %}

main_app/templates/main_app/bachelor_update_form.html
{% extends 'base.html' %}

{% block content %}

<a href="javascript:history.back()" class="back">Back</a>

<div class="title-container">
    <h1>Edit {{ bachelor.name }}</h1>
</div>

    <form action="" method="POST">
        {% csrf_token %}
        <table class="gifts">
            {{ form.as_table }}
        </table>
        <input type="submit" class="edit-bachelorbtn" value="Update Bachelor">
    </form>

{% endblock %}

main_app/templates/main_app/bachelorette_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="title-container">
  <h1>Delete Bachelorette</h1>
</div>

<h4>Are you sure you want to delete <span class="red-text">{{ bachelorette.name }}</span>?</h4>

<div class="form-container">
  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' object.game.id %}" class="cancel">Cancel</a>
  </form>
</div>

{% endblock %}

main_app/templates/main_app/bachelorette_detail.html
{% extends 'base.html' %}

{% block content %}

<a href="javascript:history.back()" class="back">Back</a>

{% if object %}
<div class="title-container">
    <h1>{{ bachelorette.name }}/{{ object.game.title }}</h1>
</div>
<div class="table-container">
    <table class="gifts">
        <thead>
            <tr>
                <th>Loved Gifts</th>
                <th>Liked Gifts</th>
                <th>Neutral Gifts</th>
                <th>Disliked Gifts</th>
                <th>Hated Gifts</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{bachelorette.loved}}</td>&nbsp;
                <td>{{bachelorette.liked}}</td>&nbsp;
                <td>{{bachelorette.neutral}}</td>&nbsp;
                <td>{{bachelorette.disliked}}</td>&nbsp;
                <td>{{bachelorette.hated}}</td>&nbsp;
            </tr>
        </tbody>
    </table>
</div>

<a href="{% url 'bachelorette_update' bachelorette.id %}">Update Bachelorette</a>&nbsp;

{% for note in bachelorette.note_set.all %}
<div class="notes-content">
    <h2>{{ note.title }}</h2>
    <p>{{ note.updated_at }}</p>
    <p class="notecontent">{{ note.content }}</p>
</div>
{% endfor %}
<a href="{% url 'bachelorette_createnote' bachelorette.id %}">Create Note</a>
{% endif %}

{% endblock %}

main_app/templates/main_app/bachelorette_form.html
{% extends 'base.html' %}

{% block content %}

<a href="javascript:history.back()" class="back">Back</a>

<div class="title-container">
    {% if object %}
    <h1>Edit {{ bachelorette.name }} </h1>
    {% else %}
    <h1>Add Bachelorette</h1>
    {% endif %}
</div>


    <form action="" method="POST">
        {% csrf_token %}
        <table class="gifts">
            {{ form.as_table }}
        </table>
        <input type="submit" value="Add Bachelorette" class="add-bachelorettebtn">
    </form>

{% endblock %}

main_app/templates/main_app/game_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="title-container">
  <h1>Delete Game</h1>
</div>

  <h4>Are you sure you want to delete <span class="red-text">{{ game.title }}</span>?</h4>

<div class="form-container">
  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' game.id %}" class="cancel">Cancel</a>
  </form>
</div>

  {% endblock %}

main_app/templates/main_app/game_form.html
{% extends 'base.html' %}

{% block content %}

<a href="javascript:history.back()" class="back">Back</a>

<div class="title-container">
    {% if object %}
    <h1>Edit {{ game.title }} </h1>
    {% else %}
    <h1>Add Game</h1>
    {% endif %}
</div>


    <form action="" method="POST">
        {% csrf_token %}
        <table class="gifts">
            {{ form.as_table }}
        </table>
        <input type="submit" value="Add Game" class="add-gamebtn">
    </form>


{% endblock %}

main_app/templates/main_app/note_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="title-container">
  <h1>Delete Note</h1>
</div>

  <h4>Are you sure you want to delete <span class="red-text">{{ note.title }}</span>?</h4>

<div class="form-container">
  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' object.game.id %}" class="cancel">Cancel</a>
  </form>
</div>

{% endblock %}

main_app/templates/main_app/note_form.html
{% extends 'base.html' %}

{% block content %}

<a href="javascript:history.back()" class="back">Back</a>


<div class="title-container">
    <h1>Add Note</h1>
</div>


<div class="form-container">
    <form action="" method="POST">
        {% csrf_token %}
        {% for item in form %}
        <div class="fieldWrapper">
            {{ item.label }} {{ item }}
            {% if item.help_text %}
            {{ item.help_text|safe }}
            {% endif %}
        </div>
        <br>
        {% endfor %}
        <input type="submit" class="enter-notebtn" value="Add New Note">
    </form>
</div>

{% endblock %}

main_app/templates/main_app/note_update_form.html
{% extends 'base.html' %}

{% block content %}
<a href="javascript:history.back()" class="back">Back</a>

<div class="title-container">
    <h1>Edit {{ note.title }}</h1>
</div>

    <form action="" method="POST">
        {% csrf_token %}
        <table class="gifts">
            {{ form.as_table }}
        </table>
        <input type="submit" class="edit-notebtn" value="Update Note">
    </form>

    
{% endblock %}